// List of valid universities (extracted from email domain mapping)
export const UNIVERSITIES = [
  // Canadian Universities
  "University of Waterloo",
  "University of Toronto",
  "McGill University",
  "University of British Columbia",
  "Queen's University",
  "McMaster University",
  "Western University",
  "University of Alberta",
  "University of Calgary",
  "Simon Fraser University",
  "York University",
  "Carleton University",
  "University of Ottawa",
  "Concordia University",
  "Dalhousie University",
  "University of New Brunswick",
  "University of Victoria",
  "University of Saskatchewan",
  "University of Manitoba",
  "Toronto Metropolitan University",
  "University of Guelph",
  "University of Windsor",
  "Brock University",
  "Lakehead University",
  "Laurentian University",
  "Nipissing University",
  "Trent University",
  "University of Ontario Institute of Technology",
  "Wilfrid Laurier University",
  "University of Regina",
  "Mount Royal University",
  "Athabasca University",
  "University of Lethbridge",
  "Brandon University",
  "University of Winnipeg",
  "Acadia University",
  "Cape Breton University",
  "Mount Saint Vincent University",
  "Saint Mary's University",
  "St. Francis Xavier University",
  "University of Prince Edward Island",
  "Memorial University of Newfoundland",
  "University of Northern British Columbia",
  "Royal Roads University",
  "Thompson Rivers University",
  "University of the Fraser Valley",
  "Vancouver Island University",
  "Bishop's University",
  "École Polytechnique de Montréal",
  "HEC Montréal",
  "Université de Montréal",
  "Université de Sherbrooke",
  "Université Laval",
  "Université du Québec à Montréal",
  "Ryerson University", // Legacy name for TMU
  
  // US Universities - Ivy League
  "Harvard University",
  "Yale University",
  "Princeton University",
  "Columbia University",
  "University of Pennsylvania",
  "Dartmouth College",
  "Brown University",
  "Cornell University",
  
  // US Universities - Top Public
  "University of California, Berkeley",
  "University of California, Los Angeles",
  "University of California, San Diego",
  "University of California, Davis",
  "University of California, Santa Barbara",
  "University of California, Irvine",
  "University of California, Riverside",
  "University of California, Santa Cruz",
  "University of California, Merced",
  "University of Michigan",
  "University of Virginia",
  "University of North Carolina at Chapel Hill",
  "University of Texas at Austin",
  "University of Wisconsin-Madison",
  "University of Illinois Urbana-Champaign",
  "University of Washington",
  "University of Florida",
  "University of Georgia",
  "Pennsylvania State University",
  "Ohio State University",
  "Michigan State University",
  "Indiana University Bloomington",
  "Purdue University",
  "University of Maryland, College Park",
  "Rutgers University",
  "University of Connecticut",
  "University of Delaware",
  "University of Vermont",
  "University of New Hampshire",
  "University of Maine",
  "University of Massachusetts Amherst",
  "University of Rhode Island",
  
  // US Universities - Top Private
  "Massachusetts Institute of Technology",
  "Stanford University",
  "University of Chicago",
  "Northwestern University",
  "Duke University",
  "Johns Hopkins University",
  "Vanderbilt University",
  "Rice University",
  "Washington University in St. Louis",
  "Emory University",
  "Georgetown University",
  "University of Notre Dame",
  "Wake Forest University",
  "Boston University",
  "Boston College",
  "New York University",
  "University of Southern California",
  "Carnegie Mellon University",
  "Georgia Institute of Technology",
  "California Institute of Technology",
  "University of Rochester",
  "Case Western Reserve University",
  "Tulane University",
  "Brandeis University",
  "Lehigh University",
  "Northeastern University",
  "Tufts University",
  "Villanova University",
  "Fordham University",
  "Syracuse University",
  "University of Miami",
  "Southern Methodist University",
  "Baylor University",
  "Texas Christian University",
  "Brigham Young University",
  "University of Denver",
  "Pepperdine University",
  "Loyola Marymount University",
  "Santa Clara University",
  "University of San Diego",
  "University of San Francisco",
  "Chapman University",
  "University of the Pacific",
  
  // US Universities - State Flagships
  "Arizona State University",
  "University of Arizona",
  "University of Arkansas",
  "Auburn University",
  "University of Alabama",
  "University of Colorado Boulder",
  "Colorado State University",
  "University of Connecticut",
  "Florida State University",
  "University of Central Florida",
  "Florida International University",
  "University of South Florida",
  "Georgia State University",
  "University of Hawaii at Manoa",
  "Boise State University",
  "University of Idaho",
  "Illinois State University",
  "Northern Illinois University",
  "Iowa State University",
  "University of Iowa",
  "Kansas State University",
  "University of Kansas",
  "University of Kentucky",
  "Louisiana State University",
  "University of Louisiana at Lafayette",
  "University of Maine",
  "University of Massachusetts Boston",
  "University of Massachusetts Lowell",
  "University of Minnesota",
  "Mississippi State University",
  "University of Mississippi",
  "University of Missouri",
  "Montana State University",
  "University of Montana",
  "University of Nebraska-Lincoln",
  "University of Nevada, Las Vegas",
  "University of Nevada, Reno",
  "University of New Hampshire",
  "New Mexico State University",
  "University of New Mexico",
  "North Carolina State University",
  "East Carolina University",
  "North Dakota State University",
  "University of North Dakota",
  "Kent State University",
  "Ohio University",
  "University of Cincinnati",
  "Oklahoma State University",
  "University of Oklahoma",
  "Oregon State University",
  "Portland State University",
  "University of Oregon",
  "Temple University",
  "University of Pittsburgh",
  "Clemson University",
  "University of South Carolina",
  "South Dakota State University",
  "University of South Dakota",
  "University of Tennessee",
  "Tennessee State University",
  "Texas A&M University",
  "Texas Tech University",
  "University of Houston",
  "Utah State University",
  "University of Utah",
  "Virginia Tech",
  "Virginia Commonwealth University",
  "Washington State University",
  "Eastern Washington University",
  "West Virginia University",
  "University of Wyoming",
  
  // US Universities - Liberal Arts & Specialized
  "Williams College",
  "Amherst College",
  "Swarthmore College",
  "Wellesley College",
  "Middlebury College",
  "Bowdoin College",
  "Pomona College",
  "Claremont McKenna College",
  "Harvey Mudd College",
  "Davidson College",
  "Washington and Lee University",
  "Colgate University",
  "Hamilton College",
  "Vassar College",
  "Grinnell College",
  "Haverford College",
  "Bates College",
  "Colby College",
  "Macalester College",
  "Oberlin College",
  "Reed College",
  "Smith College",
  "Mount Holyoke College",
  "Barnard College",
  "Bryn Mawr College",
  "Scripps College",
  "Pitzer College",
  
  // UK Universities
  "University of Oxford",
  "University of Cambridge",
  "Imperial College London",
  "University College London",
  "London School of Economics",
  "University of Edinburgh",
  "University of Manchester",
  "University of Bristol",
  "University of Warwick",
  
  // Australian Universities
  "University of New South Wales",
  "University of Melbourne",
  "University of Sydney",
  "Australian National University",
  "University of Queensland",
] as const;

export type University = typeof UNIVERSITIES[number];

export const isValidUniversity = (university: string): university is University => {
  return UNIVERSITIES.includes(university as University);
};
