-- Ensure the table exists
CREATE TABLE IF NOT EXISTS public.typing_tests_seed (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL,
    wpm NUMERIC NOT NULL,
    raw_wpm NUMERIC NOT NULL,
    accuracy NUMERIC,
    university TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Remove Foreign Key constraint on user_id if it exists to allow anonymous submissions
DO $$ 
BEGIN 
  IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'typing_tests_seed_user_id_fkey') THEN 
    ALTER TABLE public.typing_tests_seed DROP CONSTRAINT typing_tests_seed_user_id_fkey; 
  END IF; 
END $$;

-- Enable RLS
ALTER TABLE public.typing_tests_seed ENABLE ROW LEVEL SECURITY;

-- Allow public inserts (authenticated and anonymous)
DROP POLICY IF EXISTS "Enable insert for all users" ON public.typing_tests_seed;
CREATE POLICY "Enable insert for all users" ON public.typing_tests_seed FOR INSERT TO public WITH CHECK (true);

-- Allow public read
DROP POLICY IF EXISTS "Enable read for all users" ON public.typing_tests_seed;
CREATE POLICY "Enable read for all users" ON public.typing_tests_seed FOR SELECT TO public USING (true);

